language: objective-c
osx_image: xcode9
env:
  - DESTINATION="OS=11.0,name=iPhone 7" SCHEME="MoonWalker" SDK=iphonesimulator

before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - brew outdated npm || brew upgrade npm
  - npm install -g danger
  - brew outdated danger/tap/danger-swift || brew upgrade danger/tap/danger-swift
  - brew install swiftlint # This is for the Danger SwiftLint plugin.
  - carthage update --platform iOS
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
  - danger process danger-swift
  - xcodebuild clean build -project MoonWalker.xcodeproj -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c
  - xcodebuild test -project MoonWalker.xcodeproj -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c
