language: objective-c
osx_image: xcode9.4
xcode_workspace: MoonWalker.xcworkspace
xcode_scheme: MoonWalker
env:
  - DESTINATION="platform=iOS Simulator,name=iPhone 8" SCHEME="MoonWalker" SDK=iphonesimulator11.4

before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - brew outdated npm || brew upgrade npm
  - npm install -g danger
  - brew install danger/tap/danger-swift
  - brew install swiftlint # This is for the Danger SwiftLint plugin.
  - carthage update --platform iOS
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
  - danger process danger-swift
  - xcodebuild clean build -project MoonWalker.xcodeproj -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c && exit ${PIPESTATUS[0]}
  - xcodebuild test -project MoonWalker.xcodeproj -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c && exit ${PIPESTATUS[0]}
