language: objective-c
osx_image: xcode9.4
xcode_workspace: MoonWalker.xcworkspace
xcode_scheme: MoonWalker
env:
  matrix:
  - DESTINATION="platform=iOS Simulator,name=iPhone 8" SCHEME="MoonWalker" SDK=iphonesimulator11.4
  global:
    secure: OSab2t7pyQ6FBJMjLU69PpL4XRHr6ej+d2t1YNvnMc5PW1HjCoYh9gGUTGgLvoUXNcvPeRXD3Bb51G2SiTZxUVtdRg1PBqPKFWHuZRW17tL8MlH5V3fv/pIqDS2yzP4zjl1UcViMvVGcrZbvHywlB62khyKBzXs3b8ku+zQpoKHnqzgfPEWYXsro7QhmidQevv6puJJGidyC9e8bGv/5Vwnd6Bs6nLqeYJLgyAEH6xD+b+11OMDuZbgyUmEYWufBws80EmYMNBEp1BH1YnvJCYUJS1WcMGc4T7c8AQLeQgj1X+3xyaPvOC6myrHzyeN0E3oXbeIaNkQVpomd+SSHBNUXcXnx8A8kCzK6DLmyvynqJ0rgDugUgvrmQ7tFE0pqY6S0ukr8ZJIJSg5YFiBAZPaaYuVyzHYgEqjxeKMCWRBul4KUyHHsBBte1k2sOaOMCx+w2KtrZFkzapewoB2pCZj8cJ1xvETyZCDJBQo0w9OJfq5kqmNA+1IhhlAWvLcA/Ly0XmuCAqJuap6FSjONXNLzBghKY8ImBVDofqg1+ynd1K1ItHV5hlei9toHBleSp9pL/9xhhjspW8kJV7BYe0mSUzwomygIumSMsbktkAu7qMtzdSjfRpD9o1VJnKbHnnd/AbVUXE8a9E17MT8n0WsNtdEAkGdc7IycFPkqRIw=
before_install:
- brew update
- brew outdated carthage || brew upgrade carthage
- brew outdated npm || brew upgrade npm
- npm install -g danger
- brew install danger/tap/danger-swift
- brew install swiftlint
- carthage update --platform iOS
- gem install xcpretty cocoapods -no-rdoc --no-ri --no-document --quiet
script:
- set -o pipefail
- xcodebuild -version
- xcodebuild -showsdks
- danger process danger-swift
- xcodebuild clean build -project MoonWalker.xcodeproj -scheme "$SCHEME" -sdk "$SDK"
  -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty
  -c
- xcodebuild test -project MoonWalker.xcodeproj -scheme "$SCHEME" -sdk "$SDK" -destination
  "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c
- if [ $POD_LINT == "YES" ]; then pod lib lint; fi
